// DO NOT EDIT THIS FILE! THIS FILE WAS GENERATED BY `dev/tools/unicode_data_generator`.
// Unicode version: 17.0.0

// Canonical Combining Class data: 5'535 bytes

#ifndef UNI_CPP_IMPL_UNICODE_DATA_DATA_CANONICAL_COMBINING_CLASS_DATA_EMBED_HPP
#define UNI_CPP_IMPL_UNICODE_DATA_DATA_CANONICAL_COMBINING_CLASS_DATA_EMBED_HPP

#include <cstdint>
#include <array>

#include "../../embed/parse.hpp"

#include "../../embed/start_embed_code.hpp"

namespace upp::impl::unicode_data::canonical_combining_class::impl
{
    // 2'278 bytes
    inline constexpr std::array<std::uint8_t, 2278> stage1{
#embed "data/stage1.dat"
    };

    // 2'979 bytes
    inline constexpr std::array<std::uint8_t, 2979> stage2{
#embed "data/stage2.dat"
    };

    // 278 bytes
    inline constexpr std::array<std::uint16_t, 139> stage2_offsets = embed::parse<std::uint16_t, 278>(std::array<std::uint8_t, 278>{
#embed "data/stage2_offsets.dat"
    });
} // namespace upp::impl::unicode_data::canonical_combining_class::impl

#include "../../embed/end_embed_code.hpp"

#endif // UNI_CPP_IMPL_UNICODE_DATA_DATA_CANONICAL_COMBINING_CLASS_DATA_EMBED_HPP
