// DO NOT EDIT THIS FILE! THIS FILE WAS GENERATED BY `dev/tools/unicode_data_generator`.
// Unicode version: 17.0.0

#ifndef UNI_CPP_IMPL_UNICODE_DATA_DATA_CANONICAL_COMBINING_CLASS_DATA_HPP
#define UNI_CPP_IMPL_UNICODE_DATA_DATA_CANONICAL_COMBINING_CLASS_DATA_HPP

#include <cstdint>

#include "../../embed/support.hpp"

#ifdef UNI_CPP_IMPL_HAS_EMBED
#include "data_embed.hpp"
#else
#include "data_inline.hpp"
#endif

namespace upp::impl::unicode_data::canonical_combining_class::impl
{
    [[nodiscard]] constexpr std::uint8_t lookup(const std::uint64_t key) noexcept
    {
        // See `dev/docs/multistage-lookup-tables.md`.

        if (key > 0x0001E94A)
            return 0x00;

        const std::uint64_t quot = key / 55;
        const std::uint64_t rem  = key % 55;

        const std::uint32_t stage2_offset = stage2_offsets[stage1[quot]];

        return stage2[stage2_offset + rem];
    }
} // namespace upp::impl::unicode_data::canonical_combining_class::impl

#endif // UNI_CPP_IMPL_UNICODE_DATA_DATA_CANONICAL_COMBINING_CLASS_DATA_HPP
