from pathlib import Path

from .integers import format_int_as_hex
from ..datasets.interface import TestData, TestDataset

class TestEmitter:
    def __init__(self, output_dir: Path, unicode_version: str):
        self.unicode_version = unicode_version
        self.output_dir = output_dir / unicode_version / 'test_data'

    def emit(self, test_dataset: TestDataset):
        print(f'[*] Emitting {test_dataset.pretty_name()} test files')

        for test_data in test_dataset.data():
            filepath: Path = self.output_dir / (test_data.identifier + '.txt')

            self._emit_data_file(test_data, filepath)


    def _emit_data_file(self, data: TestData, filepath: Path):
        print(f'[*] Emitting test file: \'{filepath.name}\'')

        filepath.parent.mkdir(parents=True, exist_ok=True)

        with open(filepath, 'w', encoding='ascii') as file:

            file.write(f'# DO NOT EDIT THIS FILE! THIS FILE WAS GENERATED BY `dev/tools/unicode_data_generator`.\n')

            if self.unicode_version != 'latest':
                file.write(f'# Unicode version: {self.unicode_version}\n')

            for code_point, fields in sorted(data.data.items()):
                file.write(f'\n{format_int_as_hex(code_point)}:')

                for field in fields:
                    file.write(f'{format_int_as_hex(field)};')