// DO NOT EDIT THIS FILE! THIS FILE WAS GENERATED BY `dev/tools/unicode_data_generator`.
// Unicode version: 17.0.0

// Core Properties data: 33'912 bytes

#ifndef UNI_CPP_IMPL_UNICODE_DATA_DATA_CORE_PROPERTIES_DATA_EMBED_HPP
#define UNI_CPP_IMPL_UNICODE_DATA_DATA_CORE_PROPERTIES_DATA_EMBED_HPP

#include <cstdint>
#include <array>

#include "../../embed/parse.hpp"

#include "../../embed/start_embed_code.hpp"

namespace upp::impl::unicode_data::core_properties::impl
{
    // 7'737 bytes
    inline constexpr std::array<std::uint8_t, 7737> stage1{
#embed "data/stage1.dat"
    };

    // 25'287 bytes
    inline constexpr std::array<std::uint8_t, 25287> stage2{
#embed "data/stage2.dat"
    };

    // 496 bytes
    inline constexpr std::array<std::uint16_t, 248> stage2_offsets = embed::parse<std::uint16_t, 496>(std::array<std::uint8_t, 496>{
#embed "data/stage2_offsets.dat"
    });

    // 392 bytes
    inline constexpr std::array<std::uint32_t, 98> stage3 = embed::parse<std::uint32_t, 392>(std::array<std::uint8_t, 392>{
#embed "data/stage3.dat"
    });
} // namespace upp::impl::unicode_data::core_properties::impl

#include "../../embed/end_embed_code.hpp"

#endif // UNI_CPP_IMPL_UNICODE_DATA_DATA_CORE_PROPERTIES_DATA_EMBED_HPP
