// DO NOT EDIT THIS FILE! THIS FILE WAS GENERATED BY `dev/tools/unicode_data_generator`.
// Unicode version: 17.0.0

#ifndef UNI_CPP_IMPL_UNICODE_DATA_DATA_COMPOSITION_MAPPING_DATA_HPP
#define UNI_CPP_IMPL_UNICODE_DATA_DATA_COMPOSITION_MAPPING_DATA_HPP

#include <cstdint>

#include "../../embed/support.hpp"

#ifdef UNI_CPP_IMPL_HAS_EMBED
#include "data_embed.hpp"
#else
#include "data_inline.hpp"
#endif

#include "../../hash.hpp"

namespace upp::impl::unicode_data::composition_mapping::impl
{
    [[nodiscard]] constexpr std::uint32_t lookup(const std::uint64_t key) noexcept
    {
        // MPHF based on 'Easy Perfect Minimal Hashing' by Steve Hanov
        // See https://stevehanov.ca/blog/throw-away-the-keys-easy-minimal-perfect-hashing

        const auto lookup_result = [](const std::uint64_t key) static -> std::uint64_t {
            const auto d = intermediate[hash(key, 0ULL) % 0x03C1U];

            if (d < 0)
                return values[-d - 1];

            return values[hash(key, d) % 0x03C1U];
        }(key);

        const std::uint64_t actual_key = lookup_result & 0x0000003FFFFFFFFFULL;

        if (actual_key != key)
            return 0x00110000;

        return lookup_result >> 38U;
    }
} // namespace upp::impl::unicode_data::composition_mapping::impl

#endif // UNI_CPP_IMPL_UNICODE_DATA_DATA_COMPOSITION_MAPPING_DATA_HPP
