// DO NOT EDIT THIS FILE! THIS FILE WAS GENERATED BY `dev/tools/unicode_data_generator`.
// Unicode version: 17.0.0

// Composition Mapping data: 9'610 bytes

#ifndef UNI_CPP_IMPL_UNICODE_DATA_DATA_COMPOSITION_MAPPING_DATA_EMBED_HPP
#define UNI_CPP_IMPL_UNICODE_DATA_DATA_COMPOSITION_MAPPING_DATA_EMBED_HPP

#include <cstdint>
#include <array>

#include "../../embed/parse.hpp"

#include "../../embed/start_embed_code.hpp"

namespace upp::impl::unicode_data::composition_mapping::impl
{
    // 1'922 bytes
    inline constexpr std::array<std::int16_t, 961> intermediate = embed::parse<std::int16_t, 1922>(std::array<std::uint8_t, 1922>{
#embed "data/intermediate.dat"
    });

    // 7'688 bytes
    inline constexpr std::array<std::uint64_t, 961> values = embed::parse<std::uint64_t, 7688>(std::array<std::uint8_t, 7688>{
#embed "data/values.dat"
    });
} // namespace upp::impl::unicode_data::composition_mapping::impl

#include "../../embed/end_embed_code.hpp"

#endif // UNI_CPP_IMPL_UNICODE_DATA_DATA_COMPOSITION_MAPPING_DATA_EMBED_HPP
