// DO NOT EDIT THIS FILE! THIS FILE WAS GENERATED BY `dev/tools/unicode_data_generator`.
// Unicode version: 16.0.0

// Case Mapping data: 12'342 bytes

#ifndef UNI_CPP_IMPL_UNICODE_DATA_DATA_CASE_MAPPING_DATA_EMBED_HPP
#define UNI_CPP_IMPL_UNICODE_DATA_DATA_CASE_MAPPING_DATA_EMBED_HPP

#include <cstdint>
#include <array>

#include "../../embed/parse.hpp"

#include "../../embed/start_embed_code.hpp"

namespace upp::impl::unicode_data::case_mapping::impl
{
    // 1'958 bytes
    inline constexpr std::array<std::uint8_t, 1958> stage1{
#embed "data/stage1.dat"
    };

    // 6'150 bytes
    inline constexpr std::array<std::uint16_t, 3075> stage2 = embed::parse<std::uint16_t, 6150>(std::array<std::uint8_t, 6150>{
#embed "data/stage2.dat"
    });

    // 138 bytes
    inline constexpr std::array<std::uint16_t, 69> stage2_offsets = embed::parse<std::uint16_t, 138>(std::array<std::uint8_t, 138>{
#embed "data/stage2_offsets.dat"
    });

    // 2'264 bytes
    inline constexpr std::array<std::uint64_t, 283> stage3 = embed::parse<std::uint64_t, 2264>(std::array<std::uint8_t, 2264>{
#embed "data/stage3.dat"
    });

    // 496 bytes
    inline constexpr std::array<std::int32_t, 124> simple_mapping_offsets = embed::parse<std::int32_t, 496>(std::array<std::uint8_t, 496>{
#embed "data/simple_mapping_offsets.dat"
    });

    // 1'336 bytes
    inline constexpr std::array<std::uint64_t, 167> special_mappings = embed::parse<std::uint64_t, 1336>(std::array<std::uint8_t, 1336>{
#embed "data/special_mappings.dat"
    });
} // namespace upp::impl::unicode_data::case_mapping::impl

#include "../../embed/end_embed_code.hpp"

#endif // UNI_CPP_IMPL_UNICODE_DATA_DATA_CASE_MAPPING_DATA_EMBED_HPP
