// DO NOT EDIT THIS FILE! THIS FILE WAS GENERATED BY `dev/tools/unicode_data_generator`.
// Unicode version: 17.0.0

// Case Mapping data: 12'512 bytes

#ifndef UNI_CPP_IMPL_UNICODE_DATA_DATA_CASE_MAPPING_DATA_EMBED_HPP
#define UNI_CPP_IMPL_UNICODE_DATA_DATA_CASE_MAPPING_DATA_EMBED_HPP

#include <cstdint>
#include <array>

#include "../../embed/parse.hpp"

#include "../../embed/start_embed_code.hpp"

namespace upp::impl::unicode_data::case_mapping::impl
{
    // 3'132 bytes
    inline constexpr std::array<std::uint8_t, 3132> stage1{
#embed "data/stage1.dat"
    };

    // 5'070 bytes
    inline constexpr std::array<std::uint16_t, 2535> stage2 = embed::parse<std::uint16_t, 5070>(std::array<std::uint8_t, 5070>{
#embed "data/stage2.dat"
    });

    // 194 bytes
    inline constexpr std::array<std::uint16_t, 97> stage2_offsets = embed::parse<std::uint16_t, 194>(std::array<std::uint8_t, 194>{
#embed "data/stage2_offsets.dat"
    });

    // 2'280 bytes
    inline constexpr std::array<std::uint64_t, 285> stage3 = embed::parse<std::uint64_t, 2280>(std::array<std::uint8_t, 2280>{
#embed "data/stage3.dat"
    });

    // 500 bytes
    inline constexpr std::array<std::int32_t, 125> simple_mapping_offsets = embed::parse<std::int32_t, 500>(std::array<std::uint8_t, 500>{
#embed "data/simple_mapping_offsets.dat"
    });

    // 1'336 bytes
    inline constexpr std::array<std::uint64_t, 167> special_mappings = embed::parse<std::uint64_t, 1336>(std::array<std::uint8_t, 1336>{
#embed "data/special_mappings.dat"
    });
} // namespace upp::impl::unicode_data::case_mapping::impl

#include "../../embed/end_embed_code.hpp"

#endif // UNI_CPP_IMPL_UNICODE_DATA_DATA_CASE_MAPPING_DATA_EMBED_HPP
