// DO NOT EDIT THIS FILE! THIS FILE WAS GENERATED BY `dev/tools/unicode_data_generator`.
// Unicode version: 16.0.0

#ifndef UNI_CPP_IMPL_UNICODE_DATA_DATA_CASE_MAPPING_DATA_HPP
#define UNI_CPP_IMPL_UNICODE_DATA_DATA_CASE_MAPPING_DATA_HPP

#include <cstdint>

#include "../../embed/support.hpp"

#ifdef UNI_CPP_IMPL_HAS_EMBED
#include "data_embed.hpp"
#else
#include "data_inline.hpp"
#endif

namespace upp::impl::unicode_data::case_mapping::impl
{
    inline constexpr std::uint32_t greatest_code_point_with_lowercase_mapping = 0x0001E921;
    inline constexpr std::uint32_t greatest_code_point_with_uppercase_mapping = 0x0001E943;
    inline constexpr std::uint32_t greatest_code_point_with_titlecase_mapping = 0x0001E943;
    inline constexpr std::uint32_t greatest_code_point_with_casefold_mapping  = 0x0001E921;

    [[nodiscard]] constexpr std::uint64_t lookup(const std::uint32_t code_point) noexcept
    {
        // See `dev/docs/multistage-lookup-tables.md`.

        const std::uint32_t quot = code_point / 64;
        const std::uint32_t rem  = code_point % 64;

        const std::uint32_t stage2_offset = stage2_offsets[stage1[quot]];

        const auto stage2_value = stage2[stage2_offset + rem];
        return stage3[stage2_value];
    }
} // namespace upp::impl::unicode_data::case_mapping::impl

#endif // UNI_CPP_IMPL_UNICODE_DATA_DATA_CASE_MAPPING_DATA_HPP
