#pragma once
#ifndef UNI_CPP_VERSION_HPP
#define UNI_CPP_VERSION_HPP

#include "config.hpp"

// Note: These files are generated by cmake
#include "impl/version.hpp"
#include "impl/unicode_version.hpp"

#endif // UNI_CPP_VERSION_HPP