// DO NOT EDIT THIS FILE! THIS FILE WAS GENERATED BY `dev/tools/unicode_data_generator`.
// Unicode version: 17.0.0

// General Category data: 35'590 bytes

#ifndef UNI_CPP_IMPL_UNICODE_DATA_DATA_GENERAL_CATEGORY_DATA_EMBED_HPP
#define UNI_CPP_IMPL_UNICODE_DATA_DATA_GENERAL_CATEGORY_DATA_EMBED_HPP

#include <cstdint>
#include <array>

#include "../../embed/parse.hpp"

#include "../../embed/start_embed_code.hpp"

namespace upp::impl::unicode_data::general_category::impl
{
    // 6'794 bytes
    inline constexpr std::array<std::uint8_t, 6794> stage1{
#embed "data/stage1.dat"
    };

    // 28'306 bytes
    inline constexpr std::array<std::uint8_t, 28306> stage2{
#embed "data/stage2.dat"
    };

    // 490 bytes
    inline constexpr std::array<std::uint16_t, 245> stage2_offsets = embed::parse<std::uint16_t, 490>(std::array<std::uint8_t, 490>{
#embed "data/stage2_offsets.dat"
    });
} // namespace upp::impl::unicode_data::general_category::impl

#include "../../embed/end_embed_code.hpp"

#endif // UNI_CPP_IMPL_UNICODE_DATA_DATA_GENERAL_CATEGORY_DATA_EMBED_HPP
