// DO NOT EDIT THIS FILE! THIS FILE WAS GENERATED BY `dev/tools/unicode_data_generator`.
// Unicode version: 17.0.0

// Decomposition data: 83'939 bytes

#ifndef UNI_CPP_IMPL_UNICODE_DATA_DATA_DECOMPOSITION_DATA_EMBED_HPP
#define UNI_CPP_IMPL_UNICODE_DATA_DATA_DECOMPOSITION_DATA_EMBED_HPP

#include <cstdint>
#include <array>

#include "../../embed/parse.hpp"

#include "../../embed/start_embed_code.hpp"

namespace upp::impl::unicode_data::decomposition::impl
{
    // 4'065 bytes
    inline constexpr std::array<std::uint8_t, 4065> stage1{
#embed "data/stage1.dat"
    };

    // 16'640 bytes
    inline constexpr std::array<std::uint16_t, 8320> stage2 = embed::parse<std::uint16_t, 16640>(std::array<std::uint8_t, 16640>{
#embed "data/stage2.dat"
    });

    // 446 bytes
    inline constexpr std::array<std::uint16_t, 223> stage2_offsets = embed::parse<std::uint16_t, 446>(std::array<std::uint8_t, 446>{
#embed "data/stage2_offsets.dat"
    });

    // 37'592 bytes
    inline constexpr std::array<std::uint64_t, 4699> stage3 = embed::parse<std::uint64_t, 37592>(std::array<std::uint8_t, 37592>{
#embed "data/stage3.dat"
    });

    // 25'196 bytes
    inline constexpr std::array<std::uint32_t, 6299> mappings = embed::parse<std::uint32_t, 25196>(std::array<std::uint8_t, 25196>{
#embed "data/mappings.dat"
    });
} // namespace upp::impl::unicode_data::decomposition::impl

#include "../../embed/end_embed_code.hpp"

#endif // UNI_CPP_IMPL_UNICODE_DATA_DATA_DECOMPOSITION_DATA_EMBED_HPP
